name : ci

on : push

env:
  PORT: 3004
  SERVER_SECRET: ${{ secrets.SERVER_SECRET}}
  MONGODB_URI: ${{ secrets.MONGODB_URI}}
  PLATFORM_URI: http://localhost:3002
  SERVER_URI: http://localhost:3000
  SERVER_EMAIL: karanikio@auth.gr
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY}}
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          port: ${{ secrets.SSH_PORT}}
          password: ${{ secrets.SSH_PASSWORD}}
          script: |
            cd ~/se2/4/se2-backend-group-4
            git reset --hard origin/main
            git pull https://${{ secrets.CLONE_TOKEN}}@github.com/SoftwareEgnineering2-Assignment/se2-backend-group-4 main
            bash -ci 'npm install'
            bash -ci 'pm2 restart se2-backend-group-4'
          
    
